import { useMemo, useState } from 'react'
import { Check, Save, X } from 'lucide-react'
import { setAiLearningRunItemDecisionApi, type AiLearningRun } from '@/modules/settings/public'
import { batchCreatePalaceQuizQuestionsApi } from '@/modules/quiz/public'
import { Button } from '@/shared/components/ui/button'
import { Badge } from '@/shared/components/ui/badge'
import { toast } from '@/shared/feedback/toast'

type StructuredItem = Record<string, unknown> & { id: string; decision?: 'pending' | 'accepted' | 'rejected' }
function itemsOf(run: AiLearningRun, key: 'questions' | 'suggestions') { const value = run.result[key]; return Array.isArray(value) ? value.filter((item): item is StructuredItem => Boolean(item && typeof item === 'object' && typeof (item as StructuredItem).id === 'string')) : [] }
export function AiLearningRunResult({ run, palaceId, onRunChange }: { run: AiLearningRun; palaceId: number | null; onRunChange: (run: AiLearningRun) => void }) {
  const [saving, setSaving] = useState(false)
  const questions = useMemo(() => itemsOf(run, 'questions'), [run])
  const suggestions = useMemo(() => itemsOf(run, 'suggestions'), [run])
  const decide = async (item: StructuredItem, decision: 'accepted' | 'rejected' | 'pending') => onRunChange((await setAiLearningRunItemDecisionApi(run.id, item.id, decision)).item)
  const saveQuestions = async () => { if(!palaceId) return; const accepted = questions.filter(item => item.decision !== 'rejected'); if(!accepted.length) return; setSaving(true); try { await batchCreatePalaceQuizQuestionsApi(palaceId, accepted.map(item => ({ question_type: 'short_answer', stem: String(item.stem ?? ''), options: [], answer_payload: { reference_answer: String(item.answer ?? '') }, analysis: String(item.analysis ?? ''), source_meta: { source_kind: 'review_ai_learning', page_numbers: null, image_names: null, extra_prompt: run.user_prompt, ai_call_log_id: null, generated_at: new Date().toISOString(), generation_mode: 'ai_learning_workbench' } }))); toast.success(`已确认保存 ${accepted.length} 道题到题库。`) } finally { setSaving(false) } }
  if(questions.length) return <div className="space-y-2">{questions.map((item, index) => <div key={item.id} className="rounded-lg border bg-muted/20 p-3"><div className="flex items-start justify-between gap-2"><div className="font-medium">{index + 1}. {String(item.stem ?? '')}</div><Badge variant={item.decision === 'rejected' ? 'destructive' : item.decision === 'accepted' ? 'secondary' : 'outline'}>{item.decision === 'rejected' ? '已拒绝' : item.decision === 'accepted' ? '已保留' : '待审核'}</Badge></div><div className="mt-2 text-sm">答案：{String(item.answer ?? '')}</div><div className="mt-1 text-sm text-muted-foreground">{String(item.analysis ?? '')}</div><div className="mt-2 flex gap-1"><Button size="sm" variant="ghost" onClick={() => void decide(item, 'accepted')}><Check className="mr-1 size-3"/>保留</Button><Button size="sm" variant="ghost" onClick={() => void decide(item, 'rejected')}><X className="mr-1 size-3"/>拒绝</Button></div></div>)}<Button disabled={saving || !palaceId || questions.every(item => item.decision === 'rejected')} onClick={() => void saveQuestions()}><Save className="mr-2 size-4"/>确认保存未拒绝题目</Button></div>
  if(suggestions.length) return <div className="space-y-2">{suggestions.map(item => <div key={item.id} className="rounded-lg border bg-muted/20 p-3"><div className="flex justify-between gap-2"><Badge variant="outline">{String(item.type ?? '建议')}</Badge><Badge variant={item.decision === 'rejected' ? 'destructive' : item.decision === 'accepted' ? 'secondary' : 'outline'}>{item.decision === 'rejected' ? '已拒绝' : item.decision === 'accepted' ? '待修改' : '待审核'}</Badge></div><div className="mt-2 text-sm line-through opacity-60">{String(item.original ?? '')}</div><div className="mt-1 text-sm font-medium">{String(item.proposed ?? '')}</div><div className="mt-1 text-xs text-muted-foreground">{String(item.reason ?? '')}</div><div className="mt-2 flex gap-1"><Button size="sm" variant="ghost" onClick={() => void decide(item, 'accepted')}><Check className="mr-1 size-3"/>保留待修改</Button><Button size="sm" variant="ghost" onClick={() => void decide(item, 'rejected')}><X className="mr-1 size-3"/>拒绝</Button></div></div>)}</div>
  return <div className="whitespace-pre-wrap text-sm leading-6">{run.response_text}</div>
}
