import type {
  MindMapFeedbackEvent,
  MindMapFeedbackLevel,
  MindMapFeedbackOrigin,
} from '@/shared/components/mindmap-host/hostBridgeUtils'
import type { FeedbackDescriptor, FeedbackVisualKind } from './feedbackTypes'

export interface MindMapFeedbackProfile {
  visualKind: FeedbackVisualKind
  level: MindMapFeedbackLevel
  origin: MindMapFeedbackOrigin
  audioScope?: 'local' | 'global'
  hue: number
  size: number
  label?: string
  screenPulse?: FeedbackDescriptor['screenPulse']
}

const MIND_MAP_FEEDBACK_PROFILES: Record<MindMapFeedbackEvent, MindMapFeedbackProfile> = {
  quiz_nav_open_practice: {
    visualKind: 'navigation',
    level: 'action',
    origin: 'system',
    audioScope: 'global',
    hue: 214,
    size: 94,
    label: 'GO',
    screenPulse: 'navigation',
  },
  quiz_nav_question_prev: {
    visualKind: 'navigation',
    level: 'action',
    origin: 'review',
    audioScope: 'local',
    hue: 210,
    size: 72,
    label: 'PREV',
  },
  quiz_nav_question_next: {
    visualKind: 'navigation',
    level: 'action',
    origin: 'review',
    audioScope: 'local',
    hue: 222,
    size: 72,
    label: 'NEXT',
  },
  quiz_nav_scope_change: {
    visualKind: 'segment',
    level: 'action',
    origin: 'review',
    audioScope: 'global',
    hue: 26,
    size: 84,
    label: 'SCOPE',
  },
  quiz_nav_view_switch: {
    visualKind: 'mode',
    level: 'action',
    origin: 'toolbar',
    audioScope: 'global',
    hue: 36,
    size: 84,
    label: 'VIEW',
    screenPulse: 'soft',
  },
  quiz_nav_tab_switch: {
    visualKind: 'mode',
    level: 'action',
    origin: 'toolbar',
    audioScope: 'global',
    hue: 34,
    size: 88,
    label: 'TAB',
    screenPulse: 'soft',
  },
  quiz_answer_select: {
    visualKind: 'focus',
    level: 'micro',
    origin: 'review',
    audioScope: 'local',
    hue: 188,
    size: 60,
    label: 'PICK',
  },
  quiz_answer_submit: {
    visualKind: 'confirm',
    level: 'action',
    origin: 'review',
    audioScope: 'local',
    hue: 156,
    size: 82,
    label: 'SUBMIT',
  },
  quiz_answer_reset: {
    visualKind: 'mode',
    level: 'action',
    origin: 'review',
    audioScope: 'local',
    hue: 214,
    size: 78,
    label: 'RESET',
  },
  quiz_result_correct: {
    visualKind: 'reward',
    level: 'action',
    origin: 'review',
    audioScope: 'local',
    hue: 145,
    size: 84,
    label: 'RIGHT',
  },
  quiz_result_incorrect: {
    visualKind: 'danger',
    level: 'action',
    origin: 'review',
    audioScope: 'local',
    hue: 4,
    size: 84,
    label: 'MISS',
  },
  quiz_result_reveal: {
    visualKind: 'reward',
    level: 'action',
    origin: 'review',
    audioScope: 'local',
    hue: 42,
    size: 92,
    label: 'REVEAL',
  },
  quiz_result_ai_feedback_ready: {
    visualKind: 'link',
    level: 'action',
    origin: 'system',
    audioScope: 'global',
    hue: 284,
    size: 88,
    label: 'AI',
  },
  quiz_manage_create_start: {
    visualKind: 'create',
    level: 'action',
    origin: 'toolbar',
    audioScope: 'local',
    hue: 145,
    size: 82,
    label: 'ADD',
  },
  quiz_manage_edit_start: {
    visualKind: 'edit',
    level: 'action',
    origin: 'toolbar',
    audioScope: 'local',
    hue: 198,
    size: 80,
    label: 'EDIT',
  },
  quiz_manage_save: {
    visualKind: 'confirm',
    level: 'action',
    origin: 'system',
    audioScope: 'global',
    hue: 156,
    size: 84,
    label: 'SAVE',
  },
  quiz_manage_delete: {
    visualKind: 'danger',
    level: 'action',
    origin: 'system',
    audioScope: 'local',
    hue: 4,
    size: 82,
    label: 'DEL',
  },
  quiz_manage_batch_delete: {
    visualKind: 'danger',
    level: 'milestone',
    origin: 'system',
    audioScope: 'global',
    hue: 2,
    size: 104,
    label: 'PURGE',
  },
  quiz_generate_start: {
    visualKind: 'shortcut',
    level: 'action',
    origin: 'system',
    audioScope: 'global',
    hue: 262,
    size: 88,
    label: 'GEN',
  },
  quiz_generate_attach_source: {
    visualKind: 'create',
    level: 'action',
    origin: 'system',
    audioScope: 'local',
    hue: 36,
    size: 82,
    label: 'LOAD',
  },
  quiz_generate_preview_ready: {
    visualKind: 'reward',
    level: 'action',
    origin: 'system',
    audioScope: 'global',
    hue: 42,
    size: 94,
    label: 'PREVIEW',
  },
  quiz_generate_save: {
    visualKind: 'create',
    level: 'milestone',
    origin: 'system',
    audioScope: 'global',
    hue: 145,
    size: 102,
    label: 'APPLY',
  },
  quiz_generate_classify_complete: {
    visualKind: 'segment',
    level: 'milestone',
    origin: 'system',
    audioScope: 'global',
    hue: 32,
    size: 108,
    label: 'GROUP',
    screenPulse: 'celebration',
  },
  quiz_generate_cancel: {
    visualKind: 'mode',
    level: 'action',
    origin: 'system',
    audioScope: 'global',
    hue: 18,
    size: 80,
    label: 'CANCEL',
  },
  quiz_error_missing_input: {
    visualKind: 'danger',
    level: 'action',
    origin: 'system',
    audioScope: 'local',
    hue: 12,
    size: 78,
    label: 'MISS',
  },
  quiz_error_ai_failed: {
    visualKind: 'danger',
    level: 'action',
    origin: 'system',
    audioScope: 'global',
    hue: 0,
    size: 90,
    label: 'AI ERR',
  },
  quiz_error_persist_failed: {
    visualKind: 'danger',
    level: 'action',
    origin: 'system',
    audioScope: 'global',
    hue: 0,
    size: 92,
    label: 'FAIL',
  },
  quiz_error_stat_failed: {
    visualKind: 'danger',
    level: 'action',
    origin: 'system',
    audioScope: 'local',
    hue: 6,
    size: 76,
    label: 'ERR',
  },
  pointer_down: { visualKind: 'tap', level: 'micro', origin: 'pointer', hue: 210, size: 48 },
  pointer_click: { visualKind: 'tap', level: 'micro', origin: 'pointer', hue: 210, size: 56 },
  hover_pulse: { visualKind: 'hover', level: 'micro', origin: 'pointer', hue: 210, size: 42 },
  key_press: { visualKind: 'edit', level: 'micro', origin: 'keyboard', hue: 188, size: 42 },
  shortcut_trigger: {
    visualKind: 'shortcut',
    level: 'action',
    origin: 'keyboard',
    hue: 262,
    size: 82,
    label: 'CMD',
  },
  navigation: {
    visualKind: 'navigation',
    level: 'action',
    origin: 'system',
    hue: 214,
    size: 96,
    label: 'GO',
    screenPulse: 'navigation',
  },
  field_focus: {
    visualKind: 'focus',
    level: 'micro',
    origin: 'keyboard',
    hue: 198,
    size: 64,
    label: 'FOCUS',
  },
  field_commit: {
    visualKind: 'confirm',
    level: 'action',
    origin: 'keyboard',
    hue: 156,
    size: 76,
    label: 'SAVE',
  },
  toggle_on: { visualKind: 'toggle', level: 'action', origin: 'pointer', hue: 145, size: 72, label: 'ON' },
  toggle_off: { visualKind: 'toggle', level: 'action', origin: 'pointer', hue: 18, size: 72, label: 'OFF' },
  text_commit: {
    visualKind: 'confirm',
    level: 'action',
    origin: 'keyboard',
    hue: 156,
    size: 78,
    label: 'SAVE',
  },
  node_select: { visualKind: 'focus', level: 'micro', origin: 'node', hue: 214, size: 54 },
  node_edit_start: {
    visualKind: 'edit',
    level: 'action',
    origin: 'node',
    hue: 198,
    size: 76,
    label: 'EDIT',
  },
  node_create: {
    visualKind: 'create',
    level: 'action',
    origin: 'node',
    hue: 145,
    size: 84,
    label: 'ADD',
  },
  node_delete: {
    visualKind: 'danger',
    level: 'action',
    origin: 'node',
    hue: 4,
    size: 82,
    label: 'DEL',
  },
  node_move: { visualKind: 'move', level: 'micro', origin: 'node', hue: 238, size: 58 },
  drag_start: { visualKind: 'move', level: 'micro', origin: 'pointer', hue: 238, size: 54 },
  drag_drop: {
    visualKind: 'move',
    level: 'action',
    origin: 'pointer',
    hue: 238,
    size: 78,
    label: 'DROP',
  },
  context_menu: {
    visualKind: 'mode',
    level: 'action',
    origin: 'pointer',
    hue: 36,
    size: 70,
    label: 'MENU',
  },
  toolbar_action: { visualKind: 'mode', level: 'micro', origin: 'toolbar', hue: 36, size: 58 },
  mode_switch: {
    visualKind: 'mode',
    level: 'action',
    origin: 'toolbar',
    hue: 36,
    size: 86,
    label: 'MODE',
    screenPulse: 'soft',
  },
  save_success: {
    visualKind: 'confirm',
    level: 'action',
    origin: 'system',
    hue: 156,
    size: 76,
    label: 'SAVE',
  },
  save_error: {
    visualKind: 'danger',
    level: 'action',
    origin: 'system',
    hue: 4,
    size: 86,
    label: 'ERR',
  },
  import_apply: {
    visualKind: 'create',
    level: 'milestone',
    origin: 'system',
    hue: 145,
    size: 98,
    label: 'APPLY',
  },
  segment_action: {
    visualKind: 'segment',
    level: 'action',
    origin: 'node',
    hue: 26,
    size: 78,
    label: 'SEG',
  },
  category_expand: {
    visualKind: 'create',
    level: 'action',
    origin: 'review',
    hue: 42,
    size: 86,
    label: 'OPEN',
  },
  next_level_expand: {
    visualKind: 'create',
    level: 'action',
    origin: 'review',
    hue: 42,
    size: 82,
    label: 'OPEN',
  },
  card_reveal: {
    visualKind: 'reward',
    level: 'action',
    origin: 'review',
    hue: 42,
    size: 90,
    label: 'REVEAL',
  },
  branch_clear: {
    visualKind: 'reward',
    level: 'milestone',
    origin: 'review',
    hue: 145,
    size: 104,
    label: 'CLEAR',
  },
  all_clear_ready: {
    visualKind: 'reward',
    level: 'milestone',
    origin: 'review',
    hue: 42,
    size: 116,
    label: 'READY',
    screenPulse: 'celebration',
  },
  session_complete: {
    visualKind: 'reward',
    level: 'milestone',
    origin: 'review',
    hue: 42,
    size: 126,
    label: 'DONE',
    screenPulse: 'celebration',
  },
  session_reset: {
    visualKind: 'mode',
    level: 'action',
    origin: 'review',
    hue: 214,
    size: 84,
    label: 'RESET',
  },
}

export function getMindMapFeedbackProfile(event: MindMapFeedbackEvent) {
  return MIND_MAP_FEEDBACK_PROFILES[event]
}
