// Generated by `npm run openapi:types` in apps/web.
// Keep this file machine-owned; feature code should import generated contracts
// through typed wrappers in `shared/api/modules/*` or `shared/api/contracts.ts`.
export {}
