import type { MindMapDocNode, MindMapEditorState } from '@/shared/api/contracts'
import type { AiContextEnvelope, AiContextNode, AiContextScope } from './types'

type BuildOptions = { editorState: MindMapEditorState; title: string; sourceEntityId: string; sourceRevision: string; scope: AiContextScope; activeNodeUid?: string | null; manualNodeUids?: string[]; reviewNodeUids?: string[]; includeNotes?: boolean; includeAncestors?: boolean; redNodeUids?: string[]; ratings?: Map<string, number> }
type IndexedNode = { node: MindMapDocNode; uid: string; parentUid: string | null; depth: number }
const plain = (value: unknown) => typeof value === 'string' ? value.replace(/<br\s*\/?>/gi, '\n').replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ').trim() : ''
const uidOf = (node: MindMapDocNode, fallback: string) => String(node.data?.uid ?? node.data?.memoryAnkiId ?? fallback)
function indexTree(root: MindMapDocNode) { const ordered: IndexedNode[] = []; const byUid = new Map<string, IndexedNode>(); const visit = (node: MindMapDocNode, parentUid: string | null, depth: number, fallback: string) => { const uid = uidOf(node, fallback); const item = { node, uid, parentUid, depth }; ordered.push(item); byUid.set(uid, item); (node.children ?? []).forEach((child, index) => visit(child, uid, depth + 1, `${fallback}-${index}`)) }; visit(root, null, 0, 'root'); return { ordered, byUid } }
function descendants(uid: string, index: ReturnType<typeof indexTree>) { const result = new Set([uid]); let changed = true; while(changed){ changed = false; for(const item of index.ordered){ if(item.parentUid && result.has(item.parentUid) && !result.has(item.uid)){ result.add(item.uid); changed = true } } } return result }
function ancestors(uid: string, index: ReturnType<typeof indexTree>) { const result: string[] = []; let current = index.byUid.get(uid); while(current){ result.unshift(current.uid); current = current.parentUid ? index.byUid.get(current.parentUid) : undefined } return result }
export function buildAiContextEnvelope(options: BuildOptions): AiContextEnvelope { const rawDoc = options.editorState.editor_doc; const doc = typeof rawDoc === 'string' ? (() => { try { return JSON.parse(rawDoc) as { root?: MindMapDocNode } } catch { return null } })() : rawDoc as { root?: MindMapDocNode } | null; const root = doc?.root; if(!root) throw new Error('当前思维导图没有可发送的内容。'); const index = indexTree(root); const active = options.activeNodeUid && index.byUid.has(options.activeNodeUid) ? options.activeNodeUid : null; let selected = new Set<string>(); if(options.scope === 'full') selected = new Set(index.ordered.map(item => item.uid)); else if(options.scope === 'manual') selected = new Set((options.manualNodeUids ?? []).filter(uid => index.byUid.has(uid))); else if(options.scope === 'review') selected = new Set((options.reviewNodeUids ?? []).filter(uid => index.byUid.has(uid))); else if(active && options.scope === 'node') selected.add(active); else if(active && options.scope === 'ancestors') selected = new Set(ancestors(active, index)); else if(active) selected = descendants(active, index); else selected = new Set((options.reviewNodeUids ?? []).filter(uid => index.byUid.has(uid))); if(selected.size === 0) selected.add(index.ordered[0].uid); if(options.includeAncestors !== false) [...selected].forEach(uid => ancestors(uid, index).forEach(item => selected.add(item))); const red = new Set(options.redNodeUids ?? []); const nodes: AiContextNode[] = index.ordered.filter(item => selected.has(item.uid)).map(item => ({ uid: item.uid, title: plain(item.node.data?.text), body: plain(item.node.data?.text), note: options.includeNotes === false ? '' : plain(item.node.data?.note), parent_uid: item.parentUid, depth: item.depth, learning_state: red.has(item.uid) || options.ratings?.has(item.uid) ? { weak: red.has(item.uid), rating: options.ratings?.get(item.uid) ?? null } : null })); const characters = nodes.reduce((sum, node) => sum + node.title.length + node.note.length, 0); return { source_type: 'review_mindmap', source_entity_id: options.sourceEntityId, source_revision: options.sourceRevision, scope: options.scope, title: options.title, node_uids: nodes.map(node => node.uid), nodes, include_notes: options.includeNotes !== false, include_ancestors: options.includeAncestors !== false, summary: `${nodes.length} 个节点，约 ${characters} 字`, estimated_tokens: Math.ceil(characters / 1.5), truncation: [] } }

