import type { AiRuntimeOptions, ResolvedAiRuntimeMeta } from '@/shared/api/contracts'
export type AiLearningTaskKey = 'ask' | 'explain' | 'quiz' | 'correct'
export type AiContextScope = 'node' | 'ancestors' | 'subtree' | 'review' | 'full' | 'manual'
export interface AiContextNode { uid: string; title: string; body: string; note: string; parent_uid: string | null; depth: number; learning_state?: Record<string, unknown> | null }
export interface AiContextEnvelope { source_type: string; source_entity_id: string; source_revision: string; scope: AiContextScope; title: string; node_uids: string[]; nodes: AiContextNode[]; include_notes: boolean; include_ancestors: boolean; summary: string; estimated_tokens: number; truncation: string[] }
export interface AiContextSelection { kind: 'mindmap' | 'quiz_bank' | 'source'; enabled: boolean; source_entity_id?: string; source_revision?: string; label: string; content: string; truncated?: boolean }
export interface AiRunDraft { task_key: AiLearningTaskKey; context: AiContextEnvelope; user_prompt: string; output_type: string; ai_options?: AiRuntimeOptions; scenario_key?: string; entrypoint_key?: string; context_selections?: AiContextSelection[]; owner_id: string; operation_id: string; thread_id?: string; parent_run_id?: string; retry_of_run_id?: string; review_session_id?: number; palace_id?: number }
export interface AiRunPreview { system_prompt: string; context_text: string; user_prompt: string; messages: Array<{ role: string; content: string }>; estimated_tokens: number; warnings: string[] }
export interface AiLearningRun { id: string; thread_id: string; parent_run_id?: string | null; operation_id: string; scenario_key: string; entrypoint_key: string; review_session_id?: number | null; palace_id?: number | null; task_key: AiLearningTaskKey; status: 'running' | 'completed' | 'failed'; user_prompt: string; prompt_snapshot: string; context: AiContextEnvelope; context_selections: AiContextSelection[]; request: { messages?: Array<{ role: string; content: string }>; estimated_tokens?: number }; response_text: string; result: Record<string, unknown>; model_meta: Partial<ResolvedAiRuntimeMeta>; warnings: string[]; error: string; feedback: '' | 'helpful' | 'unclear' | 'dismissed'; application_status: 'previewed' | 'accepted' | 'applied' | 'dismissed'; application_result: Record<string, unknown>; deleted: boolean; deleted_at?: string | null; created_at: string; completed_at?: string | null }
