export { default } from '@/features/profile/ProfileSettingsPage'
export { default as ProfileSettingsPage } from '@/features/profile/ProfileSettingsPage'
export { default as ProfileTimerPage } from '@/features/profile/ProfileTimerPage'
export { default as ProfileAiPage } from '@/features/profile/ProfileAiPage'
export { default as ProfileBackupsPage } from '@/features/profile/ProfileBackupsPage'
export { default as ProfileFeedbackPage } from '@/features/profile/ProfileFeedbackPage'
