import { act, renderHook, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { getArticleReadingCursorApi, saveArticleReadingCursorApi, type ArticleReadingResponse } from '../../../api/articleReadingApi'
import { useArticleReadingProgress } from './useArticleReadingProgress'
vi.mock('../../../api/articleReadingApi', () => ({ getArticleReadingCursorApi: vi.fn(), saveArticleReadingCursorApi: vi.fn() }))
const get = vi.mocked(getArticleReadingCursorApi)
const save = vi.mocked(saveArticleReadingCursorApi)
const cursor = { owner_id: 'palace:1' as const, node_uid: 'saved', block_offset: 0.25, updated_at: '2026-01-01T00:00:00Z', client_id: 'other', operation_id: 'remote', client_sequence: 1, revision: 3 }

describe('article progress ownership', () => {
  beforeEach(() => { vi.useRealTimers(); localStorage.clear(); sessionStorage.clear(); get.mockReset(); save.mockReset() })
  it('offers resume without writing and ignores delayed old owner loads', async () => {
    let resolveOld!: (value: ArticleReadingResponse) => void
    get.mockImplementationOnce(() => new Promise(resolve => { resolveOld = resolve }))
    get.mockResolvedValue({ owner_id: 'palace:2', cursor: null })
    const { result, rerender } = renderHook(({ id }) => useArticleReadingProgress(id), { initialProps: { id: 'palace:1' as 'palace:1' | 'palace:2' } })
    rerender({ id: 'palace:2' })
    await act(async () => resolveOld({ owner_id: 'palace:1', cursor }))
    expect(result.current.resumeCursor).toBeNull()
    expect(save).not.toHaveBeenCalled()
  })
  it('debounces and serializes writes with latest revision', async () => {
    get.mockResolvedValue({ owner_id: 'palace:1', cursor })
    let finish!: (value: ArticleReadingResponse) => void
    save.mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    save.mockResolvedValue({ owner_id: 'palace:1', cursor: { ...cursor, revision: 5 } })
    const { result, unmount } = renderHook(() => useArticleReadingProgress('palace:1'))
    await waitFor(() => expect(result.current.resumeCursor?.node_uid).toBe('saved'))
    expect(save).not.toHaveBeenCalled()
    vi.useFakeTimers()
    act(() => { result.current.recordProgress('first'); result.current.recordProgress('second', 0.4) })
    await act(async () => { await vi.advanceTimersByTimeAsync(500) })
    expect(save).toHaveBeenCalledTimes(1)
    expect(save.mock.calls[0][1]).toMatchObject({ node_uid: 'second', expected_revision: 3 })
    act(() => result.current.recordProgress('third'))
    await act(async () => { await vi.advanceTimersByTimeAsync(1000) })
    expect(save).toHaveBeenCalledTimes(1)
    await act(async () => finish({ owner_id: 'palace:1', cursor: { ...cursor, revision: 4 } }))
    await act(async () => { await vi.advanceTimersByTimeAsync(500) })
    expect(save.mock.calls[1][1]).toMatchObject({ node_uid: 'third', expected_revision: 4 })
    expect(save.mock.calls[1][1].client_sequence).toBeGreaterThan(save.mock.calls[0][1].client_sequence)
    unmount()
    vi.useRealTimers()
  })
  it('ignores old owner save completion and retains identity across remount', async () => {
    get.mockImplementation(async owner => ({ owner_id: owner, cursor: null }))
    let finish!: (value: ArticleReadingResponse) => void
    save.mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
    save.mockResolvedValue({ owner_id: 'palace:2', cursor: null })
    const { result, rerender, unmount } = renderHook(({ id }) => useArticleReadingProgress(id), { initialProps: { id: 'palace:1' as 'palace:1' | 'palace:2' } })
    await act(async () => {})
    vi.useFakeTimers()
    act(() => result.current.recordProgress('old'))
    await act(async () => { await vi.advanceTimersByTimeAsync(500) })
    const firstIdentity = save.mock.calls[0][1]
    rerender({ id: 'palace:2' })
    await act(async () => {})
    await act(async () => finish({ owner_id: 'palace:1', cursor }))
    expect(result.current.resumeCursor).toBeNull()
    act(() => result.current.recordProgress('new'))
    await act(async () => { await vi.advanceTimersByTimeAsync(500) })
    expect(save.mock.calls[1][0]).toBe('palace:2')
    expect(save.mock.calls[1][1].expected_revision).toBe(0)
    unmount()
    const remount = renderHook(() => useArticleReadingProgress('palace:2'))
    await act(async () => {})
    act(() => remount.result.current.recordProgress('remounted'))
    await act(async () => { await vi.advanceTimersByTimeAsync(500) })
    expect(save.mock.calls[2][1].client_id).toBe(firstIdentity.client_id)
    expect(save.mock.calls[2][1].client_sequence).toBeGreaterThan(firstIdentity.client_sequence)
    remount.unmount()
    vi.useRealTimers()
  })
  it('keeps local fallback while unavailable without posting revision zero', async () => {
    get.mockRejectedValue(new Error('offline'))
    localStorage.setItem('article.reading.local.palace:1', JSON.stringify({ node_uid: 'local', block_offset: null }))
    const { result } = renderHook(() => useArticleReadingProgress('palace:1'))
    await waitFor(() => expect(result.current.error).not.toBeNull())
    expect(result.current.resumeCursor?.node_uid).toBe('local')
    act(() => result.current.recordProgress('new-local'))
    expect(JSON.parse(localStorage.getItem('article.reading.local.palace:1')!).node_uid).toBe('new-local')
    expect(save).not.toHaveBeenCalled()
  })
})
