"""batch generation workspace

Revision ID: 0025_batch_generation_workspace
Revises: 0024_quiz_learning_loop
"""

from alembic import op
import sqlalchemy as sa

revision = "0025_batch_generation_workspace"
down_revision = "0024_quiz_learning_loop"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("batch_generation_workspaces", sa.Column("id", sa.String(36), primary_key=True), sa.Column("title", sa.String(240), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("operation_id", sa.String(36), nullable=False), sa.Column("settings_json", sa.Text(), nullable=False), sa.Column("estimated_input_tokens", sa.Integer(), nullable=False), sa.Column("estimated_output_tokens", sa.Integer(), nullable=False), sa.Column("actual_input_tokens", sa.Integer(), nullable=False), sa.Column("actual_output_tokens", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_index("ix_batch_generation_workspaces_status", "batch_generation_workspaces", ["status"])
    op.create_table("batch_generation_assets", sa.Column("id", sa.String(36), primary_key=True), sa.Column("workspace_id", sa.String(36), sa.ForeignKey("batch_generation_workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("role", sa.String(24), nullable=False), sa.Column("original_name", sa.String(300), nullable=False), sa.Column("relative_path", sa.String(500), nullable=False), sa.Column("sha256", sa.String(64), nullable=False), sa.Column("file_size", sa.Integer(), nullable=False), sa.Column("page_count", sa.Integer(), nullable=False), sa.Column("text_page_count", sa.Integer(), nullable=False), sa.Column("scanned_page_count", sa.Integer(), nullable=False), sa.Column("bookmarks_json", sa.Text(), nullable=False), sa.Column("sample_text_json", sa.Text(), nullable=False), sa.Column("analysis_json", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_batch_generation_assets_workspace_id", "batch_generation_assets", ["workspace_id"])
    op.create_index("ix_batch_generation_assets_sha256", "batch_generation_assets", ["sha256"])
    op.create_table("batch_generation_books", sa.Column("id", sa.String(36), primary_key=True), sa.Column("workspace_id", sa.String(36), sa.ForeignKey("batch_generation_workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("textbook_asset_id", sa.String(36), sa.ForeignKey("batch_generation_assets.id", ondelete="SET NULL")), sa.Column("quiz_asset_id", sa.String(36), sa.ForeignKey("batch_generation_assets.id", ondelete="SET NULL")), sa.Column("title", sa.String(300), nullable=False), sa.Column("subject_id", sa.Integer(), sa.ForeignKey("subjects.id", ondelete="SET NULL")), sa.Column("default_output_mode", sa.String(24), nullable=False), sa.Column("gate_status", sa.String(32), nullable=False), sa.Column("representative_section_id", sa.String(36)), sa.Column("sort_order", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_index("ix_batch_generation_books_workspace_id", "batch_generation_books", ["workspace_id"])
    op.create_table("batch_generation_sections", sa.Column("id", sa.String(36), primary_key=True), sa.Column("book_id", sa.String(36), sa.ForeignKey("batch_generation_books.id", ondelete="CASCADE"), nullable=False), sa.Column("parent_id", sa.String(36), sa.ForeignKey("batch_generation_sections.id", ondelete="CASCADE")), sa.Column("title", sa.String(300), nullable=False), sa.Column("level", sa.Integer(), nullable=False), sa.Column("start_page", sa.Integer(), nullable=False), sa.Column("end_page", sa.Integer(), nullable=False), sa.Column("output_mode", sa.String(24), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("operation_id", sa.String(36), nullable=False), sa.Column("existing_chapter_id", sa.Integer(), sa.ForeignKey("chapters.id", ondelete="SET NULL")), sa.Column("existing_palace_id", sa.Integer(), sa.ForeignKey("palaces.id", ondelete="SET NULL")), sa.Column("match_confidence", sa.Float()), sa.Column("excluded", sa.Boolean(), nullable=False), sa.Column("sort_order", sa.Integer(), nullable=False), sa.Column("revision", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("book_id", "sort_order", name="uq_batch_section_order"))
    op.create_index("ix_batch_generation_sections_book_id", "batch_generation_sections", ["book_id"])
    op.create_index("ix_batch_generation_sections_status", "batch_generation_sections", ["status"])
    op.create_table("batch_generation_steps", sa.Column("id", sa.String(36), primary_key=True), sa.Column("section_id", sa.String(36), sa.ForeignKey("batch_generation_sections.id", ondelete="CASCADE"), nullable=False), sa.Column("kind", sa.String(32), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("operation_id", sa.String(36), nullable=False), sa.Column("model", sa.String(120), nullable=False), sa.Column("system_prompt", sa.Text(), nullable=False), sa.Column("user_prompt", sa.Text(), nullable=False), sa.Column("input_snapshot_json", sa.Text(), nullable=False), sa.Column("output_json", sa.Text(), nullable=False), sa.Column("usage_json", sa.Text(), nullable=False), sa.Column("error_json", sa.Text(), nullable=False), sa.Column("attempt_count", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("section_id", "kind", name="uq_batch_section_step"))
    op.create_index("ix_batch_generation_steps_section_id", "batch_generation_steps", ["section_id"])
    op.create_table("batch_generation_drafts", sa.Column("id", sa.String(36), primary_key=True), sa.Column("section_id", sa.String(36), sa.ForeignKey("batch_generation_sections.id", ondelete="CASCADE"), nullable=False), sa.Column("kind", sa.String(24), nullable=False), sa.Column("content_json", sa.Text(), nullable=False), sa.Column("source_revision", sa.Integer(), nullable=False), sa.Column("quality_score", sa.Float()), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("section_id", "kind", name="uq_batch_section_draft"))
    op.create_index("ix_batch_generation_drafts_section_id", "batch_generation_drafts", ["section_id"])
    op.create_table("batch_generation_quality_issues", sa.Column("id", sa.String(36), primary_key=True), sa.Column("section_id", sa.String(36), sa.ForeignKey("batch_generation_sections.id", ondelete="CASCADE"), nullable=False), sa.Column("kind", sa.String(40), nullable=False), sa.Column("severity", sa.String(16), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("details_json", sa.Text(), nullable=False), sa.Column("resolved", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_batch_generation_quality_issues_section_id", "batch_generation_quality_issues", ["section_id"])
    op.create_table("batch_generation_publish_plans", sa.Column("id", sa.String(36), primary_key=True), sa.Column("workspace_id", sa.String(36), sa.ForeignKey("batch_generation_workspaces.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("actions_json", sa.Text(), nullable=False), sa.Column("conflicts_json", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_index("ix_batch_generation_publish_plans_workspace_id", "batch_generation_publish_plans", ["workspace_id"])


def downgrade() -> None:
    for table in ["batch_generation_publish_plans", "batch_generation_quality_issues", "batch_generation_drafts", "batch_generation_steps", "batch_generation_sections", "batch_generation_books", "batch_generation_assets", "batch_generation_workspaces"]:
        op.drop_table(table)
